// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: accounts.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, user_id, source_type, name)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, source_type, name, last_synced_at, last_sync_status, last_sync_error, created_at, updated_at
`

type CreateAccountParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	SourceType string
	Name       string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.UserID,
		arg.SourceType,
		arg.Name,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceType,
		&i.Name,
		&i.LastSyncedAt,
		&i.LastSyncStatus,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts
WHERE id = $1 AND user_id = $2
`

type DeleteAccountParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, user_id, source_type, name, last_synced_at, last_sync_status, last_sync_error, created_at, updated_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceType,
		&i.Name,
		&i.LastSyncedAt,
		&i.LastSyncStatus,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByUser = `-- name: GetAccountByUser :one
SELECT id, user_id, source_type, name, last_synced_at, last_sync_status, last_sync_error, created_at, updated_at
FROM accounts
WHERE id = $1 AND user_id = $2
`

type GetAccountByUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetAccountByUser(ctx context.Context, arg GetAccountByUserParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUser, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceType,
		&i.Name,
		&i.LastSyncedAt,
		&i.LastSyncStatus,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT id, user_id, source_type, name, last_synced_at, last_sync_status, last_sync_error, created_at, updated_at
FROM accounts
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAccountsByUser(ctx context.Context, userID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceType,
			&i.Name,
			&i.LastSyncedAt,
			&i.LastSyncStatus,
			&i.LastSyncError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountName = `-- name: UpdateAccountName :one
UPDATE accounts
SET name = $3
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, source_type, name, last_synced_at, last_sync_status, last_sync_error, created_at, updated_at
`

type UpdateAccountNameParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Name   string
}

func (q *Queries) UpdateAccountName(ctx context.Context, arg UpdateAccountNameParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountName, arg.ID, arg.UserID, arg.Name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceType,
		&i.Name,
		&i.LastSyncedAt,
		&i.LastSyncStatus,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
