// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: deposits.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createDeposit = `-- name: CreateDeposit :one
INSERT INTO deposits (id, user_id, month, amount)
VALUES ($1, $2, date_trunc('month', $3::date)::date, $4)
RETURNING id, user_id, month, amount, created_at, updated_at
`

type CreateDepositParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Month  pgtype.Date
	Amount decimal.Decimal
}

func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, createDeposit,
		arg.ID,
		arg.UserID,
		arg.Month,
		arg.Amount,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeposit = `-- name: DeleteDeposit :execrows
DELETE FROM deposits
WHERE id = $1 AND user_id = $2
`

type DeleteDepositParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteDeposit(ctx context.Context, arg DeleteDepositParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeposit, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDepositsByUser = `-- name: ListDepositsByUser :many
SELECT id, user_id, month, amount, created_at, updated_at
FROM deposits
WHERE user_id = $1
ORDER BY month DESC, created_at DESC
`

func (q *Queries) ListDepositsByUser(ctx context.Context, userID uuid.UUID) ([]Deposit, error) {
	rows, err := q.db.Query(ctx, listDepositsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deposit
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Month,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
