// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fx_rates.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getLatestFxRate = `-- name: GetLatestFxRate :one
SELECT date, from_ccy, to_ccy, rate
FROM fx_rates
WHERE from_ccy = $1 AND to_ccy = $2
ORDER BY date DESC
LIMIT 1
`

type GetLatestFxRateParams struct {
	FromCcy string
	ToCcy   string
}

func (q *Queries) GetLatestFxRate(ctx context.Context, arg GetLatestFxRateParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, getLatestFxRate, arg.FromCcy, arg.ToCcy)
	var i FxRate
	err := row.Scan(
		&i.Date,
		&i.FromCcy,
		&i.ToCcy,
		&i.Rate,
	)
	return i, err
}

const upsertFxRate = `-- name: UpsertFxRate :exec
INSERT INTO fx_rates (date, from_ccy, to_ccy, rate)
VALUES ($1, $2, $3, $4)
ON CONFLICT (date, from_ccy, to_ccy) DO UPDATE SET rate = EXCLUDED.rate
`

type UpsertFxRateParams struct {
	Date    pgtype.Date
	FromCcy string
	ToCcy   string
	Rate    decimal.Decimal
}

func (q *Queries) UpsertFxRate(ctx context.Context, arg UpsertFxRateParams) error {
	_, err := q.db.Exec(ctx, upsertFxRate,
		arg.Date,
		arg.FromCcy,
		arg.ToCcy,
		arg.Rate,
	)
	return err
}
