// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instruments.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countInstruments = `-- name: CountInstruments :one
SELECT COUNT(*)::bigint
FROM instruments
WHERE
    ($1::text = '' OR ticker ILIKE '%' || $1 || '%' OR name ILIKE '%' || $1 || '%')
    AND ($2::text = '' OR asset_class = $2)
`

type CountInstrumentsParams struct {
	Q          string
	AssetClass string
}

func (q *Queries) CountInstruments(ctx context.Context, arg CountInstrumentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInstruments, arg.Q, arg.AssetClass)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createInstrument = `-- name: CreateInstrument :one
INSERT INTO instruments (id, ticker, asset_class, currency, name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, ticker, asset_class, currency, name, created_at, updated_at
`

type CreateInstrumentParams struct {
	ID         uuid.UUID
	Ticker     string
	AssetClass string
	Currency   string
	Name       string
}

func (q *Queries) CreateInstrument(ctx context.Context, arg CreateInstrumentParams) (Instrument, error) {
	row := q.db.QueryRow(ctx, createInstrument,
		arg.ID,
		arg.Ticker,
		arg.AssetClass,
		arg.Currency,
		arg.Name,
	)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.AssetClass,
		&i.Currency,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstrumentByID = `-- name: GetInstrumentByID :one
SELECT id, ticker, asset_class, currency, name, created_at, updated_at
FROM instruments
WHERE id = $1
`

func (q *Queries) GetInstrumentByID(ctx context.Context, id uuid.UUID) (Instrument, error) {
	row := q.db.QueryRow(ctx, getInstrumentByID, id)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.AssetClass,
		&i.Currency,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstrumentByTickerAssetClass = `-- name: GetInstrumentByTickerAssetClass :one
SELECT id, ticker, asset_class, currency, name, created_at, updated_at
FROM instruments
WHERE LOWER(ticker) = LOWER($1) AND asset_class = $2
`

type GetInstrumentByTickerAssetClassParams struct {
	Lower      string
	AssetClass string
}

func (q *Queries) GetInstrumentByTickerAssetClass(ctx context.Context, arg GetInstrumentByTickerAssetClassParams) (Instrument, error) {
	row := q.db.QueryRow(ctx, getInstrumentByTickerAssetClass, arg.Lower, arg.AssetClass)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.AssetClass,
		&i.Currency,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInstruments = `-- name: ListInstruments :many
SELECT
    i.id, i.ticker, i.asset_class, i.currency, i.name, i.created_at, i.updated_at,
    pr.price        AS current_price,
    pr.fetched_at   AS price_fetched_at
FROM instruments i
LEFT JOIN prices pr ON pr.instrument_id = i.id
WHERE
    ($1::text = '' OR i.ticker ILIKE '%' || $1 || '%' OR i.name ILIKE '%' || $1 || '%')
    AND ($2::text = '' OR i.asset_class = $2)
ORDER BY i.ticker
LIMIT $4 OFFSET $3
`

type ListInstrumentsParams struct {
	Q          string
	AssetClass string
	Off        int32
	Lim        int32
}

type ListInstrumentsRow struct {
	ID             uuid.UUID
	Ticker         string
	AssetClass     string
	Currency       string
	Name           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	CurrentPrice   decimal.NullDecimal
	PriceFetchedAt pgtype.Timestamptz
}

func (q *Queries) ListInstruments(ctx context.Context, arg ListInstrumentsParams) ([]ListInstrumentsRow, error) {
	rows, err := q.db.Query(ctx, listInstruments,
		arg.Q,
		arg.AssetClass,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInstrumentsRow
	for rows.Next() {
		var i ListInstrumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.AssetClass,
			&i.Currency,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentPrice,
			&i.PriceFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchInstruments = `-- name: SearchInstruments :many
SELECT id, ticker, asset_class, currency, name, created_at, updated_at
FROM instruments
WHERE ticker ILIKE '%' || $1 || '%' OR name ILIKE '%' || $1 || '%'
ORDER BY (LOWER(ticker) = LOWER($1)) DESC, ticker
LIMIT 20
`

func (q *Queries) SearchInstruments(ctx context.Context, dollar_1 *string) ([]Instrument, error) {
	rows, err := q.db.Query(ctx, searchInstruments, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instrument
	for rows.Next() {
		var i Instrument
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.AssetClass,
			&i.Currency,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
