// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: instruments.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createInstrument = `-- name: CreateInstrument :one
INSERT INTO instruments (id, ticker, asset_class, currency, name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, ticker, asset_class, currency, name, created_at, updated_at
`

type CreateInstrumentParams struct {
	ID         uuid.UUID
	Ticker     string
	AssetClass string
	Currency   string
	Name       string
}

func (q *Queries) CreateInstrument(ctx context.Context, arg CreateInstrumentParams) (Instrument, error) {
	row := q.db.QueryRow(ctx, createInstrument,
		arg.ID,
		arg.Ticker,
		arg.AssetClass,
		arg.Currency,
		arg.Name,
	)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.AssetClass,
		&i.Currency,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstrumentByID = `-- name: GetInstrumentByID :one
SELECT id, ticker, asset_class, currency, name, created_at, updated_at
FROM instruments
WHERE id = $1
`

func (q *Queries) GetInstrumentByID(ctx context.Context, id uuid.UUID) (Instrument, error) {
	row := q.db.QueryRow(ctx, getInstrumentByID, id)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.AssetClass,
		&i.Currency,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstrumentByTickerAssetClass = `-- name: GetInstrumentByTickerAssetClass :one
SELECT id, ticker, asset_class, currency, name, created_at, updated_at
FROM instruments
WHERE LOWER(ticker) = LOWER($1) AND asset_class = $2
`

type GetInstrumentByTickerAssetClassParams struct {
	Lower      string
	AssetClass string
}

func (q *Queries) GetInstrumentByTickerAssetClass(ctx context.Context, arg GetInstrumentByTickerAssetClassParams) (Instrument, error) {
	row := q.db.QueryRow(ctx, getInstrumentByTickerAssetClass, arg.Lower, arg.AssetClass)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.AssetClass,
		&i.Currency,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchInstruments = `-- name: SearchInstruments :many
SELECT id, ticker, asset_class, currency, name, created_at, updated_at
FROM instruments
WHERE ticker ILIKE '%' || $1 || '%' OR name ILIKE '%' || $1 || '%'
ORDER BY (LOWER(ticker) = LOWER($1)) DESC, ticker
LIMIT 20
`

func (q *Queries) SearchInstruments(ctx context.Context, dollar_1 *string) ([]Instrument, error) {
	rows, err := q.db.Query(ctx, searchInstruments, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instrument
	for rows.Next() {
		var i Instrument
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.AssetClass,
			&i.Currency,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
