// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portfolio_snapshots.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const listPortfolioSnapshotsByDateRange = `-- name: ListPortfolioSnapshotsByDateRange :many
SELECT user_id, snapshot_date, display_currency,
       grand_total, by_asset_class, by_currency, by_account, created_at
FROM portfolio_snapshots
WHERE user_id = $1
  AND snapshot_date BETWEEN $2 AND $3
ORDER BY snapshot_date ASC
`

type ListPortfolioSnapshotsByDateRangeParams struct {
	UserID         uuid.UUID
	SnapshotDate   pgtype.Date
	SnapshotDate_2 pgtype.Date
}

func (q *Queries) ListPortfolioSnapshotsByDateRange(ctx context.Context, arg ListPortfolioSnapshotsByDateRangeParams) ([]PortfolioSnapshot, error) {
	rows, err := q.db.Query(ctx, listPortfolioSnapshotsByDateRange, arg.UserID, arg.SnapshotDate, arg.SnapshotDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortfolioSnapshot
	for rows.Next() {
		var i PortfolioSnapshot
		if err := rows.Scan(
			&i.UserID,
			&i.SnapshotDate,
			&i.DisplayCurrency,
			&i.GrandTotal,
			&i.ByAssetClass,
			&i.ByCurrency,
			&i.ByAccount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPortfolioSnapshot = `-- name: UpsertPortfolioSnapshot :exec
INSERT INTO portfolio_snapshots (
    user_id, snapshot_date, display_currency,
    grand_total, by_asset_class, by_currency, by_account
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, snapshot_date) DO UPDATE SET
    display_currency = EXCLUDED.display_currency,
    grand_total      = EXCLUDED.grand_total,
    by_asset_class   = EXCLUDED.by_asset_class,
    by_currency      = EXCLUDED.by_currency,
    by_account       = EXCLUDED.by_account,
    created_at       = now()
`

type UpsertPortfolioSnapshotParams struct {
	UserID          uuid.UUID
	SnapshotDate    pgtype.Date
	DisplayCurrency string
	GrandTotal      decimal.Decimal
	ByAssetClass    []byte
	ByCurrency      []byte
	ByAccount       []byte
}

func (q *Queries) UpsertPortfolioSnapshot(ctx context.Context, arg UpsertPortfolioSnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertPortfolioSnapshot,
		arg.UserID,
		arg.SnapshotDate,
		arg.DisplayCurrency,
		arg.GrandTotal,
		arg.ByAssetClass,
		arg.ByCurrency,
		arg.ByAccount,
	)
	return err
}
