// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portfolio.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getUserPortfolioRows = `-- name: GetUserPortfolioRows :many
SELECT
    a.id          AS account_id,
    a.name        AS account_name,
    i.id          AS instrument_id,
    i.ticker      AS instrument_ticker,
    i.asset_class AS instrument_asset_class,
    i.currency    AS instrument_currency,
    i.name        AS instrument_name,
    p.quantity,
    pr.price,
    pr.fetched_at
FROM positions p
JOIN accounts a    ON p.account_id = a.id
JOIN instruments i ON p.instrument_id = i.id
LEFT JOIN prices pr ON pr.instrument_id = i.id
WHERE a.user_id = $1
ORDER BY a.created_at, i.ticker
`

type GetUserPortfolioRowsRow struct {
	AccountID            uuid.UUID
	AccountName          string
	InstrumentID         uuid.UUID
	InstrumentTicker     string
	InstrumentAssetClass string
	InstrumentCurrency   string
	InstrumentName       string
	Quantity             decimal.Decimal
	Price                decimal.NullDecimal
	FetchedAt            pgtype.Timestamptz
}

func (q *Queries) GetUserPortfolioRows(ctx context.Context, userID uuid.UUID) ([]GetUserPortfolioRowsRow, error) {
	rows, err := q.db.Query(ctx, getUserPortfolioRows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPortfolioRowsRow
	for rows.Next() {
		var i GetUserPortfolioRowsRow
		if err := rows.Scan(
			&i.AccountID,
			&i.AccountName,
			&i.InstrumentID,
			&i.InstrumentTicker,
			&i.InstrumentAssetClass,
			&i.InstrumentCurrency,
			&i.InstrumentName,
			&i.Quantity,
			&i.Price,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
