// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: positions.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions (account_id, instrument_id, quantity)
VALUES ($1, $2, $3)
RETURNING account_id, instrument_id, quantity, updated_at
`

type CreatePositionParams struct {
	AccountID    uuid.UUID
	InstrumentID uuid.UUID
	Quantity     decimal.Decimal
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, createPosition, arg.AccountID, arg.InstrumentID, arg.Quantity)
	var i Position
	err := row.Scan(
		&i.AccountID,
		&i.InstrumentID,
		&i.Quantity,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePosition = `-- name: DeletePosition :execrows
DELETE FROM positions
WHERE account_id = $1 AND instrument_id = $2
`

type DeletePositionParams struct {
	AccountID    uuid.UUID
	InstrumentID uuid.UUID
}

func (q *Queries) DeletePosition(ctx context.Context, arg DeletePositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePosition, arg.AccountID, arg.InstrumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAccountPositionsWithInstrument = `-- name: ListAccountPositionsWithInstrument :many
SELECT
    p.account_id,
    p.instrument_id,
    p.quantity,
    p.updated_at,
    i.id          AS i_id,
    i.ticker      AS i_ticker,
    i.asset_class AS i_asset_class,
    i.currency    AS i_currency,
    i.name        AS i_name,
    i.created_at  AS i_created_at,
    i.updated_at  AS i_updated_at
FROM positions p
JOIN instruments i ON p.instrument_id = i.id
WHERE p.account_id = $1
ORDER BY i.ticker
`

type ListAccountPositionsWithInstrumentRow struct {
	AccountID    uuid.UUID
	InstrumentID uuid.UUID
	Quantity     decimal.Decimal
	UpdatedAt    pgtype.Timestamptz
	IID          uuid.UUID
	ITicker      string
	IAssetClass  string
	ICurrency    string
	IName        string
	ICreatedAt   pgtype.Timestamptz
	IUpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListAccountPositionsWithInstrument(ctx context.Context, accountID uuid.UUID) ([]ListAccountPositionsWithInstrumentRow, error) {
	rows, err := q.db.Query(ctx, listAccountPositionsWithInstrument, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountPositionsWithInstrumentRow
	for rows.Next() {
		var i ListAccountPositionsWithInstrumentRow
		if err := rows.Scan(
			&i.AccountID,
			&i.InstrumentID,
			&i.Quantity,
			&i.UpdatedAt,
			&i.IID,
			&i.ITicker,
			&i.IAssetClass,
			&i.ICurrency,
			&i.IName,
			&i.ICreatedAt,
			&i.IUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePositionQuantity = `-- name: UpdatePositionQuantity :one
UPDATE positions
SET quantity = $3, updated_at = now()
WHERE account_id = $1 AND instrument_id = $2
RETURNING account_id, instrument_id, quantity, updated_at
`

type UpdatePositionQuantityParams struct {
	AccountID    uuid.UUID
	InstrumentID uuid.UUID
	Quantity     decimal.Decimal
}

func (q *Queries) UpdatePositionQuantity(ctx context.Context, arg UpdatePositionQuantityParams) (Position, error) {
	row := q.db.QueryRow(ctx, updatePositionQuantity, arg.AccountID, arg.InstrumentID, arg.Quantity)
	var i Position
	err := row.Scan(
		&i.AccountID,
		&i.InstrumentID,
		&i.Quantity,
		&i.UpdatedAt,
	)
	return i, err
}
