// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prices.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getPrice = `-- name: GetPrice :one
SELECT instrument_id, price, fetched_at FROM prices WHERE instrument_id = $1
`

func (q *Queries) GetPrice(ctx context.Context, instrumentID uuid.UUID) (Price, error) {
	row := q.db.QueryRow(ctx, getPrice, instrumentID)
	var i Price
	err := row.Scan(&i.InstrumentID, &i.Price, &i.FetchedAt)
	return i, err
}

const upsertPrice = `-- name: UpsertPrice :exec
INSERT INTO prices (instrument_id, price, fetched_at)
VALUES ($1, $2, now())
ON CONFLICT (instrument_id) DO UPDATE
SET price = EXCLUDED.price, fetched_at = EXCLUDED.fetched_at
`

type UpsertPriceParams struct {
	InstrumentID uuid.UUID
	Price        decimal.Decimal
}

func (q *Queries) UpsertPrice(ctx context.Context, arg UpsertPriceParams) error {
	_, err := q.db.Exec(ctx, upsertPrice, arg.InstrumentID, arg.Price)
	return err
}
