// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prices.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getPrice = `-- name: GetPrice :one
SELECT instrument_id, price, fetched_at FROM prices WHERE instrument_id = $1
`

func (q *Queries) GetPrice(ctx context.Context, instrumentID uuid.UUID) (Price, error) {
	row := q.db.QueryRow(ctx, getPrice, instrumentID)
	var i Price
	err := row.Scan(&i.InstrumentID, &i.Price, &i.FetchedAt)
	return i, err
}

const upsertGlobalPrice = `-- name: UpsertGlobalPrice :execrows
INSERT INTO prices (instrument_id, price, fetched_at)
SELECT i.id, $2, now()
FROM instruments i
WHERE i.id = $1 AND i.user_id IS NULL
ON CONFLICT (instrument_id) DO UPDATE
SET price = EXCLUDED.price, fetched_at = EXCLUDED.fetched_at
`

type UpsertGlobalPriceParams struct {
	ID    uuid.UUID
	Price decimal.Decimal
}

// Admin/cron path: only writes when the target instrument is global
// (user_id IS NULL). rows_affected = 0 means the instrument is missing or
// personal — admin must not touch personal price rows.
func (q *Queries) UpsertGlobalPrice(ctx context.Context, arg UpsertGlobalPriceParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertGlobalPrice, arg.ID, arg.Price)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPersonalPrice = `-- name: UpsertPersonalPrice :execrows
INSERT INTO prices (instrument_id, price, fetched_at)
SELECT i.id, $2, now()
FROM instruments i
WHERE i.id = $1 AND i.user_id = $3
ON CONFLICT (instrument_id) DO UPDATE
SET price = EXCLUDED.price, fetched_at = EXCLUDED.fetched_at
`

type UpsertPersonalPriceParams struct {
	ID     uuid.UUID
	Price  decimal.Decimal
	UserID uuid.NullUUID
}

// Ownership predicate is inside the same statement: the row is only written when
// the target instrument is owned by the caller. rows_affected = 0 means either
// the instrument does not exist or it does not belong to the caller (both 404).
func (q *Queries) UpsertPersonalPrice(ctx context.Context, arg UpsertPersonalPriceParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertPersonalPrice, arg.ID, arg.Price, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPrice = `-- name: UpsertPrice :exec
INSERT INTO prices (instrument_id, price, fetched_at)
VALUES ($1, $2, now())
ON CONFLICT (instrument_id) DO UPDATE
SET price = EXCLUDED.price, fetched_at = EXCLUDED.fetched_at
`

type UpsertPriceParams struct {
	InstrumentID uuid.UUID
	Price        decimal.Decimal
}

// Low-level upsert with no ownership check. Internal use only; service-level
// callers should use UpsertGlobalPrice (admin/cron path) or UpsertPersonalPrice
// (user-driven path) so ownership is enforced at the SQL level.
func (q *Queries) UpsertPrice(ctx context.Context, arg UpsertPriceParams) error {
	_, err := q.db.Exec(ctx, upsertPrice, arg.InstrumentID, arg.Price)
	return err
}
