// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const deleteOrphanPositions = `-- name: DeleteOrphanPositions :exec
DELETE FROM positions
WHERE account_id = $1
  AND NOT (instrument_id = ANY($2::uuid[]))
`

type DeleteOrphanPositionsParams struct {
	AccountID uuid.UUID
	Column2   []uuid.UUID
}

func (q *Queries) DeleteOrphanPositions(ctx context.Context, arg DeleteOrphanPositionsParams) error {
	_, err := q.db.Exec(ctx, deleteOrphanPositions, arg.AccountID, arg.Column2)
	return err
}

const getAccountCredentials = `-- name: GetAccountCredentials :one
SELECT account_id, ciphertext, nonce, key_version, created_at, updated_at
FROM account_credentials
WHERE account_id = $1
`

func (q *Queries) GetAccountCredentials(ctx context.Context, accountID uuid.UUID) (AccountCredential, error) {
	row := q.db.QueryRow(ctx, getAccountCredentials, accountID)
	var i AccountCredential
	err := row.Scan(
		&i.AccountID,
		&i.Ciphertext,
		&i.Nonce,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstrumentByExternalID = `-- name: GetInstrumentByExternalID :one
SELECT i.id, i.ticker, i.asset_class, i.currency, i.name, i.created_at, i.updated_at
FROM instruments i
JOIN instrument_external_ids x ON x.instrument_id = i.id
WHERE x.source = $1 AND x.native_id = $2
`

type GetInstrumentByExternalIDParams struct {
	Source   string
	NativeID string
}

type GetInstrumentByExternalIDRow struct {
	ID         uuid.UUID
	Ticker     string
	AssetClass string
	Currency   string
	Name       string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) GetInstrumentByExternalID(ctx context.Context, arg GetInstrumentByExternalIDParams) (GetInstrumentByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getInstrumentByExternalID, arg.Source, arg.NativeID)
	var i GetInstrumentByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.AssetClass,
		&i.Currency,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExternalIDsForInstrument = `-- name: ListExternalIDsForInstrument :many
SELECT source, native_id, instrument_id, created_at
FROM instrument_external_ids
WHERE instrument_id = $1
`

func (q *Queries) ListExternalIDsForInstrument(ctx context.Context, instrumentID uuid.UUID) ([]InstrumentExternalID, error) {
	rows, err := q.db.Query(ctx, listExternalIDsForInstrument, instrumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InstrumentExternalID
	for rows.Next() {
		var i InstrumentExternalID
		if err := rows.Scan(
			&i.Source,
			&i.NativeID,
			&i.InstrumentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncableAccounts = `-- name: ListSyncableAccounts :many
SELECT id, user_id, source_type, name, last_synced_at, last_sync_status, last_sync_error, created_at, updated_at
FROM accounts
WHERE source_type IN ('tinvest', 'bybit')
`

func (q *Queries) ListSyncableAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listSyncableAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceType,
			&i.Name,
			&i.LastSyncedAt,
			&i.LastSyncStatus,
			&i.LastSyncError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountSyncStatus = `-- name: SetAccountSyncStatus :exec
UPDATE accounts
SET last_synced_at = COALESCE($3, last_synced_at),
    last_sync_status = $2,
    last_sync_error = $4,
    updated_at = now()
WHERE id = $1
`

type SetAccountSyncStatusParams struct {
	ID             uuid.UUID
	LastSyncStatus *string
	LastSyncedAt   pgtype.Timestamptz
	LastSyncError  *string
}

func (q *Queries) SetAccountSyncStatus(ctx context.Context, arg SetAccountSyncStatusParams) error {
	_, err := q.db.Exec(ctx, setAccountSyncStatus,
		arg.ID,
		arg.LastSyncStatus,
		arg.LastSyncedAt,
		arg.LastSyncError,
	)
	return err
}

const tryLockAccountSync = `-- name: TryLockAccountSync :one
SELECT pg_try_advisory_xact_lock(hashtext('sync:' || $1::text)) AS acquired
`

func (q *Queries) TryLockAccountSync(ctx context.Context, dollar_1 string) (bool, error) {
	row := q.db.QueryRow(ctx, tryLockAccountSync, dollar_1)
	var acquired bool
	err := row.Scan(&acquired)
	return acquired, err
}

const upsertAccountCredentials = `-- name: UpsertAccountCredentials :exec
INSERT INTO account_credentials (account_id, ciphertext, nonce, key_version)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id) DO UPDATE
SET ciphertext = EXCLUDED.ciphertext,
    nonce = EXCLUDED.nonce,
    key_version = EXCLUDED.key_version,
    updated_at = now()
`

type UpsertAccountCredentialsParams struct {
	AccountID  uuid.UUID
	Ciphertext []byte
	Nonce      []byte
	KeyVersion int32
}

func (q *Queries) UpsertAccountCredentials(ctx context.Context, arg UpsertAccountCredentialsParams) error {
	_, err := q.db.Exec(ctx, upsertAccountCredentials,
		arg.AccountID,
		arg.Ciphertext,
		arg.Nonce,
		arg.KeyVersion,
	)
	return err
}

const upsertInstrumentBySeed = `-- name: UpsertInstrumentBySeed :one
WITH ins AS (
    INSERT INTO instruments (id, ticker, asset_class, currency, name)
    VALUES ($1, $2, $3, $4, $5)
    ON CONFLICT (LOWER(ticker), asset_class) DO NOTHING
    RETURNING id, ticker, asset_class, currency, name, created_at, updated_at
)
SELECT id, ticker, asset_class, currency, name, created_at, updated_at FROM ins
UNION ALL
SELECT id, ticker, asset_class, currency, name, created_at, updated_at
FROM instruments
WHERE LOWER(ticker) = LOWER($2) AND asset_class = $3
  AND NOT EXISTS (SELECT 1 FROM ins)
`

type UpsertInstrumentBySeedParams struct {
	ID         uuid.UUID
	Ticker     string
	AssetClass string
	Currency   string
	Name       string
}

type UpsertInstrumentBySeedRow struct {
	ID         uuid.UUID
	Ticker     string
	AssetClass string
	Currency   string
	Name       string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) UpsertInstrumentBySeed(ctx context.Context, arg UpsertInstrumentBySeedParams) (UpsertInstrumentBySeedRow, error) {
	row := q.db.QueryRow(ctx, upsertInstrumentBySeed,
		arg.ID,
		arg.Ticker,
		arg.AssetClass,
		arg.Currency,
		arg.Name,
	)
	var i UpsertInstrumentBySeedRow
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.AssetClass,
		&i.Currency,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertInstrumentExternalID = `-- name: UpsertInstrumentExternalID :exec
INSERT INTO instrument_external_ids (source, native_id, instrument_id)
VALUES ($1, $2, $3)
ON CONFLICT (source, native_id) DO NOTHING
`

type UpsertInstrumentExternalIDParams struct {
	Source       string
	NativeID     string
	InstrumentID uuid.UUID
}

func (q *Queries) UpsertInstrumentExternalID(ctx context.Context, arg UpsertInstrumentExternalIDParams) error {
	_, err := q.db.Exec(ctx, upsertInstrumentExternalID, arg.Source, arg.NativeID, arg.InstrumentID)
	return err
}

const upsertPosition = `-- name: UpsertPosition :exec
INSERT INTO positions (account_id, instrument_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (account_id, instrument_id) DO UPDATE
SET quantity = EXCLUDED.quantity,
    updated_at = now()
`

type UpsertPositionParams struct {
	AccountID    uuid.UUID
	InstrumentID uuid.UUID
	Quantity     decimal.Decimal
}

func (q *Queries) UpsertPosition(ctx context.Context, arg UpsertPositionParams) error {
	_, err := q.db.Exec(ctx, upsertPosition, arg.AccountID, arg.InstrumentID, arg.Quantity)
	return err
}
