// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionCookieScopes = "sessionCookie.Scopes"
)

// Defines values for AccountSyncStatus.
const (
	Failed  AccountSyncStatus = "failed"
	Pending AccountSyncStatus = "pending"
	Success AccountSyncStatus = "success"
)

// Defines values for AccountType.
const (
	Bybit   AccountType = "bybit"
	Manual  AccountType = "manual"
	Tinvest AccountType = "tinvest"
)

// Defines values for AssetClass.
const (
	Crypto  AssetClass = "crypto"
	RuBond  AssetClass = "ru_bond"
	RuEtf   AssetClass = "ru_etf"
	RuStock AssetClass = "ru_stock"
	UsEtf   AssetClass = "us_etf"
	UsStock AssetClass = "us_stock"
)

// Defines values for TInvestSubAccountType.
const (
	BROKER  TInvestSubAccountType = "BROKER"
	IIS     TInvestSubAccountType = "IIS"
	PREMIUM TInvestSubAccountType = "PREMIUM"
)

// Account defines model for Account.
type Account struct {
	CreatedAt      time.Time          `json:"createdAt"`
	Id             openapi_types.UUID `json:"id"`
	LastSyncError  *string            `json:"lastSyncError"`
	LastSyncStatus *AccountSyncStatus `json:"lastSyncStatus"`
	LastSyncedAt   *time.Time         `json:"lastSyncedAt"`
	Name           string             `json:"name"`
	Type           AccountType        `json:"type"`
	UpdatedAt      time.Time          `json:"updatedAt"`
}

// AccountDetail defines model for AccountDetail.
type AccountDetail struct {
	CreatedAt      time.Time          `json:"createdAt"`
	Id             openapi_types.UUID `json:"id"`
	LastSyncError  *string            `json:"lastSyncError"`
	LastSyncStatus *AccountSyncStatus `json:"lastSyncStatus"`
	LastSyncedAt   *time.Time         `json:"lastSyncedAt"`
	Name           string             `json:"name"`
	Positions      []Position         `json:"positions"`
	Type           AccountType        `json:"type"`
	UpdatedAt      time.Time          `json:"updatedAt"`
}

// AccountList defines model for AccountList.
type AccountList struct {
	Items []Account `json:"items"`
}

// AccountSyncStatus defines model for AccountSyncStatus.
type AccountSyncStatus string

// AccountType defines model for AccountType.
type AccountType string

// AssetClass defines model for AssetClass.
type AssetClass string

// CreateAccountRequest For type=manual only `name` and `type` are required.
// For type=tinvest also `token` and `tinvestAccountId` must be provided.
// For type=bybit also `apiKey` and `apiSecret` must be provided.
type CreateAccountRequest struct {
	// ApiKey Bybit read-only API key (required when type=bybit)
	ApiKey *string `json:"apiKey,omitempty"`

	// ApiSecret Bybit read-only API secret (required when type=bybit)
	ApiSecret *string `json:"apiSecret,omitempty"`
	Name      string  `json:"name"`

	// TinvestAccountId T-Invest sub-account id (required when type=tinvest)
	TinvestAccountId *string `json:"tinvestAccountId,omitempty"`

	// Token T-Invest read-only API token (required when type=tinvest)
	Token *string     `json:"token,omitempty"`
	Type  AccountType `json:"type"`
}

// CreateInstrumentRequest defines model for CreateInstrumentRequest.
type CreateInstrumentRequest struct {
	AssetClass AssetClass `json:"assetClass"`
	Currency   string     `json:"currency"`
	Name       string     `json:"name"`
	Ticker     string     `json:"ticker"`
}

// CreatePositionRequest defines model for CreatePositionRequest.
type CreatePositionRequest struct {
	InstrumentId openapi_types.UUID `json:"instrumentId"`

	// Quantity Decimal > 0 as string
	Quantity string `json:"quantity"`
}

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// Instrument defines model for Instrument.
type Instrument struct {
	AssetClass AssetClass         `json:"assetClass"`
	CreatedAt  time.Time          `json:"createdAt"`
	Currency   string             `json:"currency"`
	Id         openapi_types.UUID `json:"id"`
	Name       string             `json:"name"`
	Ticker     string             `json:"ticker"`
	UpdatedAt  time.Time          `json:"updatedAt"`
}

// InstrumentList defines model for InstrumentList.
type InstrumentList struct {
	Items []Instrument `json:"items"`

	// Total Total instruments matching the filter (for pagination).
	Total int `json:"total"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Portfolio defines model for Portfolio.
type Portfolio struct {
	Positions []PortfolioPosition `json:"positions"`
	Summary   PortfolioSummary    `json:"summary"`
}

// PortfolioPosition defines model for PortfolioPosition.
type PortfolioPosition struct {
	AccountId      openapi_types.UUID `json:"accountId"`
	AccountName    string             `json:"accountName"`
	AssetClass     AssetClass         `json:"assetClass"`
	Currency       string             `json:"currency"`
	InstrumentId   openapi_types.UUID `json:"instrumentId"`
	Price          *string            `json:"price"`
	PriceFetchedAt *time.Time         `json:"priceFetchedAt"`
	PriceStale     bool               `json:"priceStale"`
	Quantity       string             `json:"quantity"`
	Ticker         string             `json:"ticker"`
	ValueDisplay   *string            `json:"valueDisplay"`
	ValueNative    *string            `json:"valueNative"`
}

// PortfolioSummary defines model for PortfolioSummary.
type PortfolioSummary struct {
	ByAccount       map[string]string `json:"byAccount"`
	ByAssetClass    map[string]string `json:"byAssetClass"`
	ByCurrency      map[string]string `json:"byCurrency"`
	DisplayCurrency string            `json:"displayCurrency"`

	// GrandTotal Total in display currency
	GrandTotal string `json:"grandTotal"`
}

// Position defines model for Position.
type Position struct {
	AccountId  openapi_types.UUID `json:"accountId"`
	Instrument Instrument         `json:"instrument"`

	// Quantity Decimal as string (NUMERIC 38,18)
	Quantity  string    `json:"quantity"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// Problem RFC 7807 Problem Details
type Problem struct {
	Detail   *string            `json:"detail,omitempty"`
	Fields   *map[string]string `json:"fields,omitempty"`
	Instance *string            `json:"instance,omitempty"`
	Status   int                `json:"status"`
	Title    string             `json:"title"`
	Type     *string            `json:"type,omitempty"`
}

// TInvestPreviewRequest defines model for TInvestPreviewRequest.
type TInvestPreviewRequest struct {
	Token string `json:"token"`
}

// TInvestPreviewResponse defines model for TInvestPreviewResponse.
type TInvestPreviewResponse struct {
	SubAccounts []TInvestSubAccount `json:"subAccounts"`
}

// TInvestSubAccount defines model for TInvestSubAccount.
type TInvestSubAccount struct {
	Id   string                `json:"id"`
	Name string                `json:"name"`
	Type TInvestSubAccountType `json:"type"`
}

// TInvestSubAccountType defines model for TInvestSubAccount.Type.
type TInvestSubAccountType string

// UpdateAccountRequest defines model for UpdateAccountRequest.
type UpdateAccountRequest struct {
	Name string `json:"name"`
}

// UpdatePositionRequest defines model for UpdatePositionRequest.
type UpdatePositionRequest struct {
	// Quantity Decimal > 0 as string
	Quantity string `json:"quantity"`
}

// User defines model for User.
type User struct {
	CreatedAt       time.Time           `json:"createdAt"`
	DisplayCurrency string              `json:"displayCurrency"`
	Email           openapi_types.Email `json:"email"`
	Id              openapi_types.UUID  `json:"id"`
}

// AccountId defines model for AccountId.
type AccountId = openapi_types.UUID

// InstrumentId defines model for InstrumentId.
type InstrumentId = openapi_types.UUID

// Conflict RFC 7807 Problem Details
type Conflict = Problem

// NotFound RFC 7807 Problem Details
type NotFound = Problem

// Unauthorized RFC 7807 Problem Details
type Unauthorized = Problem

// ValidationError RFC 7807 Problem Details
type ValidationError = Problem

// ListInstrumentsParams defines parameters for ListInstruments.
type ListInstrumentsParams struct {
	// Q Filter by ticker or name (case-insensitive substring).
	Q          *string     `form:"q,omitempty" json:"q,omitempty"`
	AssetClass *AssetClass `form:"assetClass,omitempty" json:"assetClass,omitempty"`
	Limit      *int        `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *int        `form:"offset,omitempty" json:"offset,omitempty"`
}

// SearchInstrumentsParams defines parameters for SearchInstruments.
type SearchInstrumentsParams struct {
	Q string `form:"q" json:"q"`
}

// GetPortfolioParams defines parameters for GetPortfolio.
type GetPortfolioParams struct {
	// Currency Display currency. Defaults to user's preference.
	Currency *string `form:"currency,omitempty" json:"currency,omitempty"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = CreateAccountRequest

// PreviewTInvestAccountsJSONRequestBody defines body for PreviewTInvestAccounts for application/json ContentType.
type PreviewTInvestAccountsJSONRequestBody = TInvestPreviewRequest

// UpdateAccountJSONRequestBody defines body for UpdateAccount for application/json ContentType.
type UpdateAccountJSONRequestBody = UpdateAccountRequest

// CreatePositionJSONRequestBody defines body for CreatePosition for application/json ContentType.
type CreatePositionJSONRequestBody = CreatePositionRequest

// UpdatePositionJSONRequestBody defines body for UpdatePosition for application/json ContentType.
type UpdatePositionJSONRequestBody = UpdatePositionRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateInstrumentJSONRequestBody defines body for CreateInstrument for application/json ContentType.
type CreateInstrumentJSONRequestBody = CreateInstrumentRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List user accounts
	// (GET /accounts)
	ListAccounts(w http.ResponseWriter, r *http.Request)
	// Create account
	// (POST /accounts)
	CreateAccount(w http.ResponseWriter, r *http.Request)
	// Preview T-Invest sub-accounts for a token
	// (POST /accounts/tinvest/preview)
	PreviewTInvestAccounts(w http.ResponseWriter, r *http.Request)
	// Delete account
	// (DELETE /accounts/{accountId})
	DeleteAccount(w http.ResponseWriter, r *http.Request, accountId AccountId)
	// Get account with positions
	// (GET /accounts/{accountId})
	GetAccount(w http.ResponseWriter, r *http.Request, accountId AccountId)
	// Update account (rename)
	// (PATCH /accounts/{accountId})
	UpdateAccount(w http.ResponseWriter, r *http.Request, accountId AccountId)
	// Add position to account
	// (POST /accounts/{accountId}/positions)
	CreatePosition(w http.ResponseWriter, r *http.Request, accountId AccountId)
	// Delete position
	// (DELETE /accounts/{accountId}/positions/{instrumentId})
	DeletePosition(w http.ResponseWriter, r *http.Request, accountId AccountId, instrumentId InstrumentId)
	// Update position quantity
	// (PUT /accounts/{accountId}/positions/{instrumentId})
	UpdatePosition(w http.ResponseWriter, r *http.Request, accountId AccountId, instrumentId InstrumentId)
	// Trigger an immediate sync for a brokerage account
	// (POST /accounts/{accountId}/sync)
	SyncAccount(w http.ResponseWriter, r *http.Request, accountId AccountId)
	// Login with email and password
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout current session
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Get current user
	// (GET /auth/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// List instruments with optional search and pagination
	// (GET /instruments)
	ListInstruments(w http.ResponseWriter, r *http.Request, params ListInstrumentsParams)
	// Create instrument manually
	// (POST /instruments)
	CreateInstrument(w http.ResponseWriter, r *http.Request)
	// Search instruments by ticker or name
	// (GET /instruments/search)
	SearchInstruments(w http.ResponseWriter, r *http.Request, params SearchInstrumentsParams)
	// Aggregated portfolio across all accounts
	// (GET /portfolio)
	GetPortfolio(w http.ResponseWriter, r *http.Request, params GetPortfolioParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List user accounts
// (GET /accounts)
func (_ Unimplemented) ListAccounts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create account
// (POST /accounts)
func (_ Unimplemented) CreateAccount(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Preview T-Invest sub-accounts for a token
// (POST /accounts/tinvest/preview)
func (_ Unimplemented) PreviewTInvestAccounts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete account
// (DELETE /accounts/{accountId})
func (_ Unimplemented) DeleteAccount(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get account with positions
// (GET /accounts/{accountId})
func (_ Unimplemented) GetAccount(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update account (rename)
// (PATCH /accounts/{accountId})
func (_ Unimplemented) UpdateAccount(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add position to account
// (POST /accounts/{accountId}/positions)
func (_ Unimplemented) CreatePosition(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete position
// (DELETE /accounts/{accountId}/positions/{instrumentId})
func (_ Unimplemented) DeletePosition(w http.ResponseWriter, r *http.Request, accountId AccountId, instrumentId InstrumentId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update position quantity
// (PUT /accounts/{accountId}/positions/{instrumentId})
func (_ Unimplemented) UpdatePosition(w http.ResponseWriter, r *http.Request, accountId AccountId, instrumentId InstrumentId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Trigger an immediate sync for a brokerage account
// (POST /accounts/{accountId}/sync)
func (_ Unimplemented) SyncAccount(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login with email and password
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout current session
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user
// (GET /auth/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List instruments with optional search and pagination
// (GET /instruments)
func (_ Unimplemented) ListInstruments(w http.ResponseWriter, r *http.Request, params ListInstrumentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create instrument manually
// (POST /instruments)
func (_ Unimplemented) CreateInstrument(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search instruments by ticker or name
// (GET /instruments/search)
func (_ Unimplemented) SearchInstruments(w http.ResponseWriter, r *http.Request, params SearchInstrumentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Aggregated portfolio across all accounts
// (GET /portfolio)
func (_ Unimplemented) GetPortfolio(w http.ResponseWriter, r *http.Request, params GetPortfolioParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAccounts operation middleware
func (siw *ServerInterfaceWrapper) ListAccounts(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccounts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateAccount(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PreviewTInvestAccounts operation middleware
func (siw *ServerInterfaceWrapper) PreviewTInvestAccounts(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PreviewTInvestAccounts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAccount operation middleware
func (siw *ServerInterfaceWrapper) DeleteAccount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", chi.URLParam(r, "accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAccount(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccount operation middleware
func (siw *ServerInterfaceWrapper) GetAccount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", chi.URLParam(r, "accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccount(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAccount operation middleware
func (siw *ServerInterfaceWrapper) UpdateAccount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", chi.URLParam(r, "accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAccount(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePosition operation middleware
func (siw *ServerInterfaceWrapper) CreatePosition(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", chi.URLParam(r, "accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePosition(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePosition operation middleware
func (siw *ServerInterfaceWrapper) DeletePosition(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", chi.URLParam(r, "accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	// ------------- Path parameter "instrumentId" -------------
	var instrumentId InstrumentId

	err = runtime.BindStyledParameterWithOptions("simple", "instrumentId", chi.URLParam(r, "instrumentId"), &instrumentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instrumentId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePosition(w, r, accountId, instrumentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePosition operation middleware
func (siw *ServerInterfaceWrapper) UpdatePosition(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", chi.URLParam(r, "accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	// ------------- Path parameter "instrumentId" -------------
	var instrumentId InstrumentId

	err = runtime.BindStyledParameterWithOptions("simple", "instrumentId", chi.URLParam(r, "instrumentId"), &instrumentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instrumentId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePosition(w, r, accountId, instrumentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SyncAccount operation middleware
func (siw *ServerInterfaceWrapper) SyncAccount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", chi.URLParam(r, "accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SyncAccount(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInstruments operation middleware
func (siw *ServerInterfaceWrapper) ListInstruments(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInstrumentsParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "assetClass" -------------

	err = runtime.BindQueryParameter("form", true, false, "assetClass", r.URL.Query(), &params.AssetClass)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "assetClass", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInstruments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateInstrument operation middleware
func (siw *ServerInterfaceWrapper) CreateInstrument(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateInstrument(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchInstruments operation middleware
func (siw *ServerInterfaceWrapper) SearchInstruments(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchInstrumentsParams

	// ------------- Required query parameter "q" -------------

	if paramValue := r.URL.Query().Get("q"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchInstruments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPortfolio operation middleware
func (siw *ServerInterfaceWrapper) GetPortfolio(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPortfolioParams

	// ------------- Optional query parameter "currency" -------------

	err = runtime.BindQueryParameter("form", true, false, "currency", r.URL.Query(), &params.Currency)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "currency", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPortfolio(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/accounts", wrapper.ListAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/accounts", wrapper.CreateAccount)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/accounts/tinvest/preview", wrapper.PreviewTInvestAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/accounts/{accountId}", wrapper.DeleteAccount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/accounts/{accountId}", wrapper.GetAccount)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/accounts/{accountId}", wrapper.UpdateAccount)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/accounts/{accountId}/positions", wrapper.CreatePosition)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/accounts/{accountId}/positions/{instrumentId}", wrapper.DeletePosition)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/accounts/{accountId}/positions/{instrumentId}", wrapper.UpdatePosition)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/accounts/{accountId}/sync", wrapper.SyncAccount)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/instruments", wrapper.ListInstruments)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/instruments", wrapper.CreateInstrument)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/instruments/search", wrapper.SearchInstruments)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/portfolio", wrapper.GetPortfolio)
	})

	return r
}

type ConflictApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type ValidationErrorApplicationProblemPlusJSONResponse Problem

type ListAccountsRequestObject struct {
}

type ListAccountsResponseObject interface {
	VisitListAccountsResponse(w http.ResponseWriter) error
}

type ListAccounts200JSONResponse AccountList

func (response ListAccounts200JSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListAccounts401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListAccounts401ApplicationProblemPlusJSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateAccountRequestObject struct {
	Body *CreateAccountJSONRequestBody
}

type CreateAccountResponseObject interface {
	VisitCreateAccountResponse(w http.ResponseWriter) error
}

type CreateAccount201JSONResponse Account

func (response CreateAccount201JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateAccount401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response CreateAccount401ApplicationProblemPlusJSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateAccount422ApplicationProblemPlusJSONResponse struct {
	ValidationErrorApplicationProblemPlusJSONResponse
}

func (response CreateAccount422ApplicationProblemPlusJSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type PreviewTInvestAccountsRequestObject struct {
	Body *PreviewTInvestAccountsJSONRequestBody
}

type PreviewTInvestAccountsResponseObject interface {
	VisitPreviewTInvestAccountsResponse(w http.ResponseWriter) error
}

type PreviewTInvestAccounts200JSONResponse TInvestPreviewResponse

func (response PreviewTInvestAccounts200JSONResponse) VisitPreviewTInvestAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PreviewTInvestAccounts401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PreviewTInvestAccounts401ApplicationProblemPlusJSONResponse) VisitPreviewTInvestAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PreviewTInvestAccounts422ApplicationProblemPlusJSONResponse struct {
	ValidationErrorApplicationProblemPlusJSONResponse
}

func (response PreviewTInvestAccounts422ApplicationProblemPlusJSONResponse) VisitPreviewTInvestAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAccountRequestObject struct {
	AccountId AccountId `json:"accountId"`
}

type DeleteAccountResponseObject interface {
	VisitDeleteAccountResponse(w http.ResponseWriter) error
}

type DeleteAccount204Response struct {
}

func (response DeleteAccount204Response) VisitDeleteAccountResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAccount401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response DeleteAccount401ApplicationProblemPlusJSONResponse) VisitDeleteAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAccount404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response DeleteAccount404ApplicationProblemPlusJSONResponse) VisitDeleteAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAccountRequestObject struct {
	AccountId AccountId `json:"accountId"`
}

type GetAccountResponseObject interface {
	VisitGetAccountResponse(w http.ResponseWriter) error
}

type GetAccount200JSONResponse AccountDetail

func (response GetAccount200JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAccount401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetAccount401ApplicationProblemPlusJSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAccount404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetAccount404ApplicationProblemPlusJSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAccountRequestObject struct {
	AccountId AccountId `json:"accountId"`
	Body      *UpdateAccountJSONRequestBody
}

type UpdateAccountResponseObject interface {
	VisitUpdateAccountResponse(w http.ResponseWriter) error
}

type UpdateAccount200JSONResponse Account

func (response UpdateAccount200JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAccount401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response UpdateAccount401ApplicationProblemPlusJSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAccount404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response UpdateAccount404ApplicationProblemPlusJSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAccount422ApplicationProblemPlusJSONResponse struct {
	ValidationErrorApplicationProblemPlusJSONResponse
}

func (response UpdateAccount422ApplicationProblemPlusJSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreatePositionRequestObject struct {
	AccountId AccountId `json:"accountId"`
	Body      *CreatePositionJSONRequestBody
}

type CreatePositionResponseObject interface {
	VisitCreatePositionResponse(w http.ResponseWriter) error
}

type CreatePosition201JSONResponse Position

func (response CreatePosition201JSONResponse) VisitCreatePositionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreatePosition401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response CreatePosition401ApplicationProblemPlusJSONResponse) VisitCreatePositionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreatePosition404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response CreatePosition404ApplicationProblemPlusJSONResponse) VisitCreatePositionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreatePosition409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response CreatePosition409ApplicationProblemPlusJSONResponse) VisitCreatePositionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreatePosition422ApplicationProblemPlusJSONResponse struct {
	ValidationErrorApplicationProblemPlusJSONResponse
}

func (response CreatePosition422ApplicationProblemPlusJSONResponse) VisitCreatePositionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type DeletePositionRequestObject struct {
	AccountId    AccountId    `json:"accountId"`
	InstrumentId InstrumentId `json:"instrumentId"`
}

type DeletePositionResponseObject interface {
	VisitDeletePositionResponse(w http.ResponseWriter) error
}

type DeletePosition204Response struct {
}

func (response DeletePosition204Response) VisitDeletePositionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeletePosition401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response DeletePosition401ApplicationProblemPlusJSONResponse) VisitDeletePositionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeletePosition404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response DeletePosition404ApplicationProblemPlusJSONResponse) VisitDeletePositionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdatePositionRequestObject struct {
	AccountId    AccountId    `json:"accountId"`
	InstrumentId InstrumentId `json:"instrumentId"`
	Body         *UpdatePositionJSONRequestBody
}

type UpdatePositionResponseObject interface {
	VisitUpdatePositionResponse(w http.ResponseWriter) error
}

type UpdatePosition200JSONResponse Position

func (response UpdatePosition200JSONResponse) VisitUpdatePositionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdatePosition401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response UpdatePosition401ApplicationProblemPlusJSONResponse) VisitUpdatePositionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdatePosition404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response UpdatePosition404ApplicationProblemPlusJSONResponse) VisitUpdatePositionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdatePosition422ApplicationProblemPlusJSONResponse struct {
	ValidationErrorApplicationProblemPlusJSONResponse
}

func (response UpdatePosition422ApplicationProblemPlusJSONResponse) VisitUpdatePositionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type SyncAccountRequestObject struct {
	AccountId AccountId `json:"accountId"`
}

type SyncAccountResponseObject interface {
	VisitSyncAccountResponse(w http.ResponseWriter) error
}

type SyncAccount200JSONResponse Account

func (response SyncAccount200JSONResponse) VisitSyncAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SyncAccount401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response SyncAccount401ApplicationProblemPlusJSONResponse) VisitSyncAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SyncAccount404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response SyncAccount404ApplicationProblemPlusJSONResponse) VisitSyncAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SyncAccount422ApplicationProblemPlusJSONResponse struct {
	ValidationErrorApplicationProblemPlusJSONResponse
}

func (response SyncAccount422ApplicationProblemPlusJSONResponse) VisitSyncAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	SetCookie string
}

type Login200JSONResponse struct {
	Body    User
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type Login401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response Login401ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Login422ApplicationProblemPlusJSONResponse struct {
	ValidationErrorApplicationProblemPlusJSONResponse
}

func (response Login422ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse User

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMe401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetMe401ApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse Health

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListInstrumentsRequestObject struct {
	Params ListInstrumentsParams
}

type ListInstrumentsResponseObject interface {
	VisitListInstrumentsResponse(w http.ResponseWriter) error
}

type ListInstruments200JSONResponse InstrumentList

func (response ListInstruments200JSONResponse) VisitListInstrumentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListInstruments401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListInstruments401ApplicationProblemPlusJSONResponse) VisitListInstrumentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateInstrumentRequestObject struct {
	Body *CreateInstrumentJSONRequestBody
}

type CreateInstrumentResponseObject interface {
	VisitCreateInstrumentResponse(w http.ResponseWriter) error
}

type CreateInstrument201JSONResponse Instrument

func (response CreateInstrument201JSONResponse) VisitCreateInstrumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateInstrument401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response CreateInstrument401ApplicationProblemPlusJSONResponse) VisitCreateInstrumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateInstrument422ApplicationProblemPlusJSONResponse struct {
	ValidationErrorApplicationProblemPlusJSONResponse
}

func (response CreateInstrument422ApplicationProblemPlusJSONResponse) VisitCreateInstrumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type SearchInstrumentsRequestObject struct {
	Params SearchInstrumentsParams
}

type SearchInstrumentsResponseObject interface {
	VisitSearchInstrumentsResponse(w http.ResponseWriter) error
}

type SearchInstruments200JSONResponse InstrumentList

func (response SearchInstruments200JSONResponse) VisitSearchInstrumentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchInstruments401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response SearchInstruments401ApplicationProblemPlusJSONResponse) VisitSearchInstrumentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetPortfolioRequestObject struct {
	Params GetPortfolioParams
}

type GetPortfolioResponseObject interface {
	VisitGetPortfolioResponse(w http.ResponseWriter) error
}

type GetPortfolio200JSONResponse Portfolio

func (response GetPortfolio200JSONResponse) VisitGetPortfolioResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPortfolio401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetPortfolio401ApplicationProblemPlusJSONResponse) VisitGetPortfolioResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List user accounts
	// (GET /accounts)
	ListAccounts(ctx context.Context, request ListAccountsRequestObject) (ListAccountsResponseObject, error)
	// Create account
	// (POST /accounts)
	CreateAccount(ctx context.Context, request CreateAccountRequestObject) (CreateAccountResponseObject, error)
	// Preview T-Invest sub-accounts for a token
	// (POST /accounts/tinvest/preview)
	PreviewTInvestAccounts(ctx context.Context, request PreviewTInvestAccountsRequestObject) (PreviewTInvestAccountsResponseObject, error)
	// Delete account
	// (DELETE /accounts/{accountId})
	DeleteAccount(ctx context.Context, request DeleteAccountRequestObject) (DeleteAccountResponseObject, error)
	// Get account with positions
	// (GET /accounts/{accountId})
	GetAccount(ctx context.Context, request GetAccountRequestObject) (GetAccountResponseObject, error)
	// Update account (rename)
	// (PATCH /accounts/{accountId})
	UpdateAccount(ctx context.Context, request UpdateAccountRequestObject) (UpdateAccountResponseObject, error)
	// Add position to account
	// (POST /accounts/{accountId}/positions)
	CreatePosition(ctx context.Context, request CreatePositionRequestObject) (CreatePositionResponseObject, error)
	// Delete position
	// (DELETE /accounts/{accountId}/positions/{instrumentId})
	DeletePosition(ctx context.Context, request DeletePositionRequestObject) (DeletePositionResponseObject, error)
	// Update position quantity
	// (PUT /accounts/{accountId}/positions/{instrumentId})
	UpdatePosition(ctx context.Context, request UpdatePositionRequestObject) (UpdatePositionResponseObject, error)
	// Trigger an immediate sync for a brokerage account
	// (POST /accounts/{accountId}/sync)
	SyncAccount(ctx context.Context, request SyncAccountRequestObject) (SyncAccountResponseObject, error)
	// Login with email and password
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout current session
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Get current user
	// (GET /auth/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// List instruments with optional search and pagination
	// (GET /instruments)
	ListInstruments(ctx context.Context, request ListInstrumentsRequestObject) (ListInstrumentsResponseObject, error)
	// Create instrument manually
	// (POST /instruments)
	CreateInstrument(ctx context.Context, request CreateInstrumentRequestObject) (CreateInstrumentResponseObject, error)
	// Search instruments by ticker or name
	// (GET /instruments/search)
	SearchInstruments(ctx context.Context, request SearchInstrumentsRequestObject) (SearchInstrumentsResponseObject, error)
	// Aggregated portfolio across all accounts
	// (GET /portfolio)
	GetPortfolio(ctx context.Context, request GetPortfolioRequestObject) (GetPortfolioResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAccounts operation middleware
func (sh *strictHandler) ListAccounts(w http.ResponseWriter, r *http.Request) {
	var request ListAccountsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAccounts(ctx, request.(ListAccountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAccounts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAccountsResponseObject); ok {
		if err := validResponse.VisitListAccountsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAccount operation middleware
func (sh *strictHandler) CreateAccount(w http.ResponseWriter, r *http.Request) {
	var request CreateAccountRequestObject

	var body CreateAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAccount(ctx, request.(CreateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAccountResponseObject); ok {
		if err := validResponse.VisitCreateAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PreviewTInvestAccounts operation middleware
func (sh *strictHandler) PreviewTInvestAccounts(w http.ResponseWriter, r *http.Request) {
	var request PreviewTInvestAccountsRequestObject

	var body PreviewTInvestAccountsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PreviewTInvestAccounts(ctx, request.(PreviewTInvestAccountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PreviewTInvestAccounts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PreviewTInvestAccountsResponseObject); ok {
		if err := validResponse.VisitPreviewTInvestAccountsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAccount operation middleware
func (sh *strictHandler) DeleteAccount(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	var request DeleteAccountRequestObject

	request.AccountId = accountId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAccount(ctx, request.(DeleteAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAccountResponseObject); ok {
		if err := validResponse.VisitDeleteAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAccount operation middleware
func (sh *strictHandler) GetAccount(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	var request GetAccountRequestObject

	request.AccountId = accountId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAccount(ctx, request.(GetAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAccountResponseObject); ok {
		if err := validResponse.VisitGetAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAccount operation middleware
func (sh *strictHandler) UpdateAccount(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	var request UpdateAccountRequestObject

	request.AccountId = accountId

	var body UpdateAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAccount(ctx, request.(UpdateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateAccountResponseObject); ok {
		if err := validResponse.VisitUpdateAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePosition operation middleware
func (sh *strictHandler) CreatePosition(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	var request CreatePositionRequestObject

	request.AccountId = accountId

	var body CreatePositionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePosition(ctx, request.(CreatePositionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePosition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePositionResponseObject); ok {
		if err := validResponse.VisitCreatePositionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeletePosition operation middleware
func (sh *strictHandler) DeletePosition(w http.ResponseWriter, r *http.Request, accountId AccountId, instrumentId InstrumentId) {
	var request DeletePositionRequestObject

	request.AccountId = accountId
	request.InstrumentId = instrumentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeletePosition(ctx, request.(DeletePositionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeletePosition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeletePositionResponseObject); ok {
		if err := validResponse.VisitDeletePositionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdatePosition operation middleware
func (sh *strictHandler) UpdatePosition(w http.ResponseWriter, r *http.Request, accountId AccountId, instrumentId InstrumentId) {
	var request UpdatePositionRequestObject

	request.AccountId = accountId
	request.InstrumentId = instrumentId

	var body UpdatePositionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdatePosition(ctx, request.(UpdatePositionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdatePosition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdatePositionResponseObject); ok {
		if err := validResponse.VisitUpdatePositionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SyncAccount operation middleware
func (sh *strictHandler) SyncAccount(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	var request SyncAccountRequestObject

	request.AccountId = accountId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SyncAccount(ctx, request.(SyncAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SyncAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SyncAccountResponseObject); ok {
		if err := validResponse.VisitSyncAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListInstruments operation middleware
func (sh *strictHandler) ListInstruments(w http.ResponseWriter, r *http.Request, params ListInstrumentsParams) {
	var request ListInstrumentsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListInstruments(ctx, request.(ListInstrumentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInstruments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListInstrumentsResponseObject); ok {
		if err := validResponse.VisitListInstrumentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateInstrument operation middleware
func (sh *strictHandler) CreateInstrument(w http.ResponseWriter, r *http.Request) {
	var request CreateInstrumentRequestObject

	var body CreateInstrumentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateInstrument(ctx, request.(CreateInstrumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateInstrument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateInstrumentResponseObject); ok {
		if err := validResponse.VisitCreateInstrumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchInstruments operation middleware
func (sh *strictHandler) SearchInstruments(w http.ResponseWriter, r *http.Request, params SearchInstrumentsParams) {
	var request SearchInstrumentsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchInstruments(ctx, request.(SearchInstrumentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchInstruments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchInstrumentsResponseObject); ok {
		if err := validResponse.VisitSearchInstrumentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPortfolio operation middleware
func (sh *strictHandler) GetPortfolio(w http.ResponseWriter, r *http.Request, params GetPortfolioParams) {
	var request GetPortfolioRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPortfolio(ctx, request.(GetPortfolioRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPortfolio")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPortfolioResponseObject); ok {
		if err := validResponse.VisitGetPortfolioResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9Q77XLbNravgsHtzHXm0pLsJLepM/mROknraT48UdIfN/FtIPJIQk0CDAA6UT2a6c6+",
	"RP/uI+yPznQ7nd1XUN5oBx8iQRKiZFt2tv9EEjjn4JyD861zHPMs5wyYkvjgHOdEkAwUCPP0MI55wdRR",
	"oh8owwc4J2qKI8xIBvgAk/J7hAW8L6iABB8oUUCEZTyFjOiNYy4yovABLgqqV6pZrjdLJSib4Pk8wkdM",
	"KlFk0IGK+kuugm2uN8ucMwnmjIecjVMaK/075kwBMz9Jnqc0Jopy1s8FH6WQ/c+PkjP9rUL2hYAxPsD/",
	"1a+42LdfZf/Y7rIoE5CxoLkGhw/wS5C8EDGg2CFHO9Cb9CKUFBYr3MLzCD/n6gkvWPJZSGNcobHBPo/w",
	"a0YKNeWC/gQ3Ss1zrpDGDEwZthhivicpTQzCx0JwcZP0VKjRmNBU0zNfKp9/Y8xVEjwHoahVs1iApv+h",
	"quloQhTsKppBW1EjTJMN9DnCKZFqOGNxyQxWpCkZpbC8Gyt3DBVRhaGOpOmLMT54080Ydzhv6/wkaqDz",
	"wHeedi2R9t6ftz/YFxtR+kovnUe4yJOLMX/uW5g32DDeEORWRp48ffAnJSQ++hFipZE7Wh6BIjS9MLPx",
	"PGqqUs4l1SpoHqiCTK7VaLejYh8mQpBZ66AV6PZJTqqzPKUyoOIlKRvRVJ2vmyQLrIOxdU0GVmR6myzi",
	"GKTEEXYXNcI5sERL9ySgbb7CeFAywgqSaqlTdgZSC3s0G1EVhiElqMOUyBohovhBKh6faqdV/DDiLLG/",
	"QI216sjyayHdu1jMcsWDKA6N1jliX8L7Aqwg6lbqCRdIb31gyUecpTP0TuvvO0RYgt7pj+8QEYCWnO69",
	"ZeUud1ZEUsnRO8VPgS332S9lWPAOZYVUaAQoF/yMJnU4hlMOCsnpdzBzYEhOhxALUMH9WlI1vbJ728f8",
	"2sAXQJJdc8KHx0foFGZoZ3ko9GEKzKPlFo5wRj4+BTZRU3zwv3cinFG2fLwX4HdJ6WbYpVm7MQF7+/fW",
	"UrA0g/62waC2bS+wrSmpNv2vdo+smGUx2nWBHKJJkHgHrZt/QTK08nTgrrPPrL4AAftNRgyiLbiLhv3x",
	"zX7ICtkrWUWw3q1sqHHNPHSSU62cRzguhAAWz2x4rhQIzcL/f/Nw9/9Ozm9Hd+df4M30Zn8jvYlPQQRQ",
	"DXa/6v2we3K+F+0PQhgbXHNwIv/U3lEcfav5ufRYK7lJGynD2jDpfUGYoipgRx5BTDOSorfFYHAb0AAR",
	"idy+CMNHkuU6TMF7g/VxQj1JKVGGzvktkFRLoXkwWbmyEjU/XYvabQthqnRzi0p58XD2cnq8YRC8Olos",
	"Fbr1aStR4WaKfpF4sRLXNsIsT/itSEvbZ0XSgH3Wr1GlzRJlRMVTyiZITQGNaapAoJ0xFygnE8pMRnSr",
	"h415oZkOfCpTTJmCCYgVgd2ShhAnnvIJXW0BIHPxdCk6+6buIu7eCWhLTqT8wEXSdKwNf7y3v04FlhhL",
	"gKFjHHOhxjylvH2Gy4TyDtjqmD7CssgyImYbwxq69S2j4t5HnYmBd8KSqLah8SORtdfZrX6+6lZvw5e2",
	"Tc1FXUouaAwbZdxm5RNQ8fRqSbGBM1Qk9dky4jwFwppO7iKm8IykBTyiMk/JbKMDmQ3PiaJnmzCgoVZ+",
	"2dCXdNR0oGuNa3nexhFqnOrU2GF1VeoKO5p5tRySJEavSXpcW7Qi2vQQjWb1tPAqkA497b08nMTy6LDr",
	"KkwEYcmrbueAHCDkyaNb7k3MNTwNVtXOG3nSCEtzO2aH1iKlzd3q+tiyDCnRzvPXzx6/PDpEt+9Fe/du",
	"NULM3t0QXVeNVPwL552xdn+6g5JlTbR1wJdPDtGX9wZfIrcC2TqXbGXxSVn/ah1vTCFNrng79LEIi8Pu",
	"IhBT39nfb0co2uIoa1srobRrvh1ZZrWtD0JwIftn5fYNkiaNPOqK5V/ZxPlYwBmFDytjozLvvli23KTH",
	"QNmEDNtPCSQzxcjd280jHAd7WG5dWyL0sXRQ60FsB9VJUHHWFqGXVb6vX7747vFLHOGjoyGO8PHLx8+O",
	"Xj8L1PDWVZZD9L82V7Nd9asf4VKVolCxYzUJa7PySybZ3UR1ptGvpStXXLXbEnCLm2epq3ORyyW0IS1Z",
	"Qmx70eq0bQ5p6wdxIaiaDfUFc/cSpKScHXJ+SqHsuMb2sey5Sp80V4U1TTHKxrwt4mMQUptuZIt1NnFU",
	"gugYrodL24pfZIya2As9PD7SkRsIaSEMenu9gWYSz4GRnOIDfLs36N02GZaaGtL7xDMoE1uZ1aI3Jlb7",
	"eazT5tIeNLq9+4NBR7/wYn1CvxkS6BXq94iPUUnvPMJ3BnuroJZk9mvN1rmfzlmYhQRRQY2wIhPpeXmJ",
	"T+YmYQuwptY/cG10kOprnsy2xpZgj2JeV2nXKWyIZm/bogmJxZKXXFIaEb6zv79+U7NFXZeiJWEpwrAE",
	"51Gl6X1X/u7n1t+6ykGgKeHwgkQElUV2W1YnLEECVCGYNEWcdKmeZ4Sa3M1vBMi3bGfx908/L/65+H3x",
	"66efP/1l8fvit8U/UB8tfln8svib/vGvTz8vfl38sfjt018Xf9zqodcSEjSaGeivj9AIxlyUp0TGSOkg",
	"SvK3TC8xahwThnIan6IPUxpPa70IxVFGNfdsT6iuyC7ycJ69dtu3r9HhoGsjlR5cGxEu5Apo+NCToxHz",
	"59R1Ry8KtZskGnOBiFXQDa7BeZnHzK3qp6CgbeQemfe+kauJ5E4oONE7rmATLNDuTeU0T51BFne3MYjC",
	"ju4bUCtPuXU35+YXAvrmFiCX4X0OJn4DqjQ0H6iaoqpeuco/eoNuKyYxqiX9qo86PzGxSDxti6MWpl+T",
	"KQqmAjdsiTqcqyXvxi7SViyUpblUnx0BOvy9dTF71K9V8q+kXB2BW1nnus7IrZnk3XDoVvU1riF2u7B6",
	"Db5av6GcIN2OPj5MktJ86SCo7Rm8ZswGCtk/96vqG3jOmpb9CVxnXtEb4tAVbH20dnFtctlc30Kt8gzX",
	"fHvDJZob9g1dt/dP7BzK++gVzC90G+WMxdvyDI1of8biqeCMFzKdobHpMcoq/jF5n2mGldG2SybdeJ5F",
	"0XvLntlhwTI2t8kiurO/H0rANNqbCz6DaY4ZMf5TadMrQScTEIgwRLMMEqp1S6uGE81I8FMQZLJJbaBQ",
	"037KJ5T51YBGIcx8vh5rU5vNuGEjY2q+oYobn0wgQZTdRxKURK7Kicq65hRI4v7aMgS1W5U/K7xVA0fS",
	"5EGv17uPvlUqf8HS2X00JBkMqYIHT8nH++iYqOmDfugvJjefb7sSLz54c1KrF2op2YzIlI+tNVgOq3jK",
	"VahpQ7G4dWQrNUt/3yRAcELRyxu1TAPDdY/VUlgdRNn2xqpM+Bngz6Byh476Qtr+4VULvDqRjX2YQXZM",
	"zezgT13s+NYtuUaeuAnGAFdefNetlfQMGEiJcsFH4B1RzqSCzB3SGz/rLPUfeetasV5jMN4Oro1myE6W",
	"IC6QTvbQTkwk7FImgWm/eWaKofY+m7E20x55X4CYVd2R99j/25nXdbu7vul2HoRYm3LZ0D96402rwKY0",
	"o6oGMYExKVLlSCUf7cjeslvonkIDfGEEfDyWsALDYM1M4Mk1KmhjkjKgqMd2ehGSshzua922Gjb+IKWx",
	"xTy3Qw5IAhHx1Fnl5SCldyF8atZ1dY78wY7rKw+0J91vuEDgj978J7d3Ktkh+z+cdLZSsg1717d6sdLs",
	"Dc3nTsO3ymKt/uPshSzY5722z5bTyFu+rZavtfva8hWdMsz9Ud9VrrmaB17jrh41Bux66JE1qxIpbsKD",
	"/9Y+FMagP8MqR+XN51UC2HS24VolXXEiZJuXHxGZTARMyHLa+apSfujAQYLyCkcsuJSIpGmotV7J9WTe",
	"iGxawxRvTjTPJIizsFSf8pikKIEztJML/pFCgs4oQd9TBVrHDkmSzG7hCBcixQe4T3Jqsn9Hynk5nGFj",
	"Je2Tl+GDDhD952rwoHxXFSu8l/Vb5K0tpXMy/3cAAAD//90KITYpQAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
