FROM golang:1.26-alpine

RUN apk add --no-cache git curl \
    && go install github.com/air-verse/air@v1.65.1 \
    && go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.31.1 \
    && go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.7.0

WORKDIR /workspace/apps/api

EXPOSE 8080

CMD ["sh", "-c", "go mod tidy && air -c .air.toml"]
